/* Market scenario database for drills */
export type Scenario = {
  id: string;
  title: string;
  market: string;
  timeframe: string;
  context: string;
  setup: string;
  question: string;
  options: string[];
  correct: number;
  explain: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
};

export const SCENARIOS: Scenario[] = [
  {
    id: "s0",
    title: "Breakout Retest BTC",
    market: "BTC/USDT",
    timeframe: "4H",
    context: "BTC consolidates under 98k for 11 days.",
    setup: "Volume expands on break, first retest holds.",
    question: "Best action?",
    options: ["Long on retest with stop below", "Short the breakout", "Market buy without stop", "Wait for 1m scalp only"],
    correct: 0,
    explain: "Retest after breakout with volume is classic continuation.",
    difficulty: 2,
    tags: ["breakout","btc"],
  },
  {
    id: "s1",
    title: "Failed Breakdown ETH",
    market: "ETH/USDT",
    timeframe: "1H",
    context: "ETH sweeps Asia low and reclaims.",
    setup: "CVD turns up, funding flat.",
    question: "This is often…",
    options: ["Bullish reclaim / stop hunt", "Guaranteed dump", "Time to short", "Irrelevant"],
    correct: 0,
    explain: "Sweep + reclaim traps shorts.",
    difficulty: 2,
    tags: ["reclaim","eth"],
  },
  {
    id: "s2",
    title: "Overextended SOL",
    market: "SOL/USDT",
    timeframe: "15m",
    context: "SOL +18% in 6 hours, RSI 86.",
    setup: "Lower TF shows exhaustion wicks.",
    question: "Risk-managed play?",
    options: ["Wait pullback / scale out longs", "Add full size", "Short with no stop", "Ignore RSI"],
    correct: 0,
    explain: "Extension needs mean reversion patience.",
    difficulty: 1,
    tags: ["momentum","sol"],
  },
  {
    id: "s3",
    title: "Range Fade",
    market: "BNB/USDT",
    timeframe: "1H",
    context: "BNB oscillates 580–610 for a week.",
    setup: "Price tags range high third time, volume fades.",
    question: "Edge?",
    options: ["Fade high with tight stop above", "Breakout long blindly", "Yolo short mid-range", "No trade ever"],
    correct: 0,
    explain: "Range fades work until break; manage risk.",
    difficulty: 2,
    tags: ["range"],
  },
  {
    id: "s4",
    title: "News Spike",
    market: "BTC/USDT",
    timeframe: "5m",
    context: "CPI print, 2% candle in seconds.",
    setup: "Spread widens, book thins.",
    question: "First rule?",
    options: ["Do not chase the first spike", "Market long immediately", "Max leverage", "Disable stops"],
    correct: 0,
    explain: "Liquidity vacuum — wait structure.",
    difficulty: 1,
    tags: ["news"],
  },
  {
    id: "s5",
    title: "Higher TF Short",
    market: "ETH/USDT",
    timeframe: "1D",
    context: "Daily lower high under declining 200 EMA.",
    setup: "4H pullback into supply.",
    question: "Bias?",
    options: ["Short pullbacks in downtrend", "Long every dip", "Ignore HTF", "Only scalp 1m"],
    correct: 0,
    explain: "Trade with higher timeframe.",
    difficulty: 2,
    tags: ["trend"],
  },
  {
    id: "s6",
    title: "Funding Extreme",
    market: "BTC/USDT",
    timeframe: "8H",
    context: "Perp funding +0.12% for 6 prints.",
    setup: "Price stalls at resistance.",
    question: "Implication?",
    options: ["Longs overcrowded — caution", "Guaranteed moon", "Shorts crowded", "No meaning"],
    correct: 0,
    explain: "Elevated funding = long squeeze risk.",
    difficulty: 2,
    tags: ["funding"],
  },
  {
    id: "s7",
    title: "Liquidity Grab",
    market: "XRP/USDT",
    timeframe: "15m",
    context: "Equal highs twice, then spike through and reverse.",
    setup: "Closes back inside range.",
    question: "Name the pattern context?",
    options: ["Stop hunt / liquidity grab", "Clean breakout", "Accumulation only", "Halving"],
    correct: 0,
    explain: "Engineered liquidity then reverse.",
    difficulty: 3,
    tags: ["liquidity"],
  },
  {
    id: "s8",
    title: "EMA Stack Bull",
    market: "TON/USDT",
    timeframe: "1H",
    context: "Price above 9/21/55 EMA fanning up.",
    setup: "Pullback kisses 21 EMA.",
    question: "Continuation entry?",
    options: ["Long near 21 EMA with structure stop", "Short EMA", "Wait days", "Market short"],
    correct: 0,
    explain: "EMA stack supports trend entries.",
    difficulty: 2,
    tags: ["ema"],
  },
  {
    id: "s9",
    title: "Double Bottom",
    market: "DOGE/USDT",
    timeframe: "4H",
    context: "Two lows equal, neckline break.",
    setup: "Volume on neckline break rises.",
    question: "Confirmation?",
    options: ["Close above neckline + retest", "Wick only", "Tweet", "Ignore volume"],
    correct: 0,
    explain: "Classic reversal needs confirmation.",
    difficulty: 1,
    tags: ["reversal"],
  },
  {
    id: "s10",
    title: "Bear Flag",
    market: "AVAX/USDT",
    timeframe: "1H",
    context: "Sharp drop then tight ascending channel.",
    setup: "Flag break continues down.",
    question: "Trade idea?",
    options: ["Short flag break", "Long flag", "No stop short", "Spot only"],
    correct: 0,
    explain: "Flags continue prior impulse.",
    difficulty: 2,
    tags: ["continuation"],
  },
  {
    id: "s11",
    title: "Session Open",
    market: "BTC/USDT",
    timeframe: "5m",
    context: "London open, range of Asia defined.",
    setup: "Fake break both sides common.",
    question: "Plan?",
    options: ["Trade after open structure forms", "First second market orders", "Predict direction", "Sleep"],
    correct: 0,
    explain: "Let session establish.",
    difficulty: 2,
    tags: ["sessions"],
  },
  {
    id: "s12",
    title: "Correlation Trap",
    market: "ETH/USDT",
    timeframe: "1H",
    context: "Long ETH and long BTC momentum alts heavily.",
    setup: "All risk one way.",
    question: "Problem?",
    options: ["Heat / correlated exposure", "Perfect hedge", "No risk", "Always fine"],
    correct: 0,
    explain: "Portfolio heat multiplies.",
    difficulty: 2,
    tags: ["risk"],
  },
  {
    id: "s13",
    title: "Gap Fill",
    market: "BNB/USDT",
    timeframe: "15m",
    context: "Weekend gap up 3%.",
    setup: "First hours fade toward gap.",
    question: "Often?",
    options: ["Partial gap fill then decide", "Never fills", "Always moons", "Ignore"],
    correct: 0,
    explain: "Gaps attract price, not destiny.",
    difficulty: 2,
    tags: ["gap"],
  },
  {
    id: "s14",
    title: "Order Block",
    market: "BTC/USDT",
    timeframe: "1H",
    context: "Last bullish candle before impulse down.",
    setup: "Price returns to block.",
    question: "ICT-style idea?",
    options: ["Reaction short from OB", "Blind long", "No invalidation", "Only RSI"],
    correct: 0,
    explain: "Define invalidation always.",
    difficulty: 3,
    tags: ["smc"],
  },
  {
    id: "s15",
    title: "Whick Rejection",
    market: "SOL/USDT",
    timeframe: "5m",
    context: "Long upper wick into prior day high.",
    setup: "Close weak mid-range.",
    question: "Read?",
    options: ["Supply rejection", "Demand", "Breakout success", "Neutral always"],
    correct: 0,
    explain: "Wicks show rejection.",
    difficulty: 1,
    tags: ["priceaction"],
  },
  {
    id: "s16",
    title: "Trendline Break",
    market: "ETH/USDT",
    timeframe: "4H",
    context: "Rising TL 3 touches, break + close.",
    setup: "Retest fails as resistance.",
    question: "Follow-through?",
    options: ["Short retest failure", "Long break", "Ignore close", "No plan"],
    correct: 0,
    explain: "Break and failed retest.",
    difficulty: 2,
    tags: ["structure"],
  },
  {
    id: "s17",
    title: "Macro Risk Off",
    market: "BTC/USDT",
    timeframe: "1D",
    context: "DXY spike, yields up.",
    setup: "Crypto bleeds with Nasdaq.",
    question: "Bias until change?",
    options: ["Defensive / reduce risk", "Max long", "Ignore macro", "Only memecoins"],
    correct: 0,
    explain: "Macro sets wind direction.",
    difficulty: 2,
    tags: ["macro"],
  },
  {
    id: "s18",
    title: "Scalp vs Swing",
    market: "BTC/USDT",
    timeframe: "1m",
    context: "You hold a swing thesis but scalp opposite.",
    setup: "Conflicted PnL.",
    question: "Fix?",
    options: ["One timeframe thesis at a time", "Mix freely", "No journal", "More leverage"],
    correct: 0,
    explain: "Alignment beats noise.",
    difficulty: 1,
    tags: ["process"],
  },
  {
    id: "s19",
    title: "Post Stop Discipline",
    market: "ETH/USDT",
    timeframe: "15m",
    context: "Stopped out correctly, price reverses to target.",
    setup: "Pain of being right then wrong.",
    question: "Correct review?",
    options: ["Process win if plan followed", "Revenge re-enter", "Disable stops forever", "Quit"],
    correct: 0,
    explain: "Judge process not single outcome.",
    difficulty: 1,
    tags: ["psychology"],
  },
];

export function scenariosByTag(tag: string) {
  return SCENARIOS.filter(s => s.tags.includes(tag) || tag === "all");
}
export function randomScenario(seed = Date.now()) {
  return SCENARIOS[seed % SCENARIOS.length];
}
