/* Deterministic learning runtime: no market/network dependency. */
window.SA_ENGINE=(()=>{const intervals=[1,3,7,16,35];const clamp=n=>Math.max(0,Math.min(1,n));
function initialPlayer(){return {version:2,level:0,phase:'context',cards:Object.fromEntries(SA_DATA.skillNodes.map(x=>[x.name,{...x}])),events:[],decisions:[],reviewQueue:[],settings:{reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,leftHanded:false,textScale:1,sound:false}}}
function termLevel(s){if(!s||s.attempts<2||s.recognition<.55)return'plain';if(s.stability<.9||s.transfer<.75)return'guided';return'technical'}
function mastered(s){return s.recognition>=.85&&s.application>=.80&&s.transfer>=.75&&s.explanation>=.75&&s.stability>=.90&&!s.criticalRiskError}
function schedule(s,now=new Date()){let idx=Math.min(intervals.length-1,Math.max(0,Math.floor((s.stability||0)*intervals.length)));let d=new Date(now);d.setUTCDate(d.getUTCDate()+intervals[idx]);return d.toISOString()}
function updateCard(s,{correct=false,application=false,transfer=false,explanation=0,confidence=.5,riskError=false,now=new Date()}={}){let n={...s};n.attempts++;n.recognition=clamp(n.recognition*.72+(correct?1:0)*.28);n.application=clamp(n.application*.78+(application?1:0)*.22);n.transfer=clamp(n.transfer*.82+(transfer?1:0)*.18);n.explanation=clamp(n.explanation*.75+explanation*.25);let calibrated=correct?1-Math.abs(1-confidence):1-confidence;n.stability=clamp(n.stability*.82+calibrated*.18);n.criticalRiskError=!!riskError;n.lastSeenAt=now.toISOString();n.nextReviewAt=schedule(n,now);return n}
function gap(s,ctx={}){if(ctx.interfaceFailure)return'interface gap';if(ctx.emotional)return'emotional gap';if(ctx.riskError)return'discipline gap';if((s.recognition||0)<.55)return'knowledge gap';if((s.application||0)<.65)return'recognition gap';if((s.transfer||0)<.75)return'transfer gap';return'stability gap'}
function practiceFor(g){return {'knowledge gap':'explanation + worked example','recognition gap':'interleaved contrast cases','transfer gap':'new asset, same card','discipline gap':'no-trade / risk protocol','emotional gap':'pause protocol, no battle','interface gap':'accessibility alternative','stability gap':'delayed mixed recall'}[g]}
function rng(seed=1){let s=seed>>>0;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}
function candles(seed=1,n=24){let r=rng(seed),p=100;return Array.from({length:n},(_,i)=>{let o=p,c=Math.max(20,o+(r()-.48)*8),h=Math.max(o,c)+r()*3,l=Math.min(o,c)-r()*3;p=c;return{i,o:+o.toFixed(2),h:+h.toFixed(2),l:+l.toFixed(2),c:+c.toFixed(2)}})}
function riskSize({deposit,riskPct,entry,stop}){let risk=deposit*riskPct/100,dist=Math.abs(entry-stop);if(!(deposit>0&&riskPct>0&&riskPct<=5&&dist>0))return{ok:false,error:'invalid risk geometry'};return{ok:true,risk:+risk.toFixed(2),size:+(risk/dist).toFixed(4)}}
function dqi(x){let dims=['decision','protocol','evidence','followup','risk','invalidation','discipline','resistance'];let base=dims.reduce((a,k)=>a+(+x[k]||0),0)/dims.length;let penalty=x.riskError?35:0;return Math.max(0,Math.min(100,Math.round(base-penalty)))}
function validateEvent(e){let req=['eventId','playerId','scenarioId','level','chapter','cardIds','phase','latencyMs','hintsUsed','timestamp'];return req.every(k=>Object.hasOwn(e,k))&&Array.isArray(e.cardIds)&&e.latencyMs>=0}
function event(name,p={}){let e={eventId:crypto.randomUUID?.()||String(Date.now()),playerId:'local-prototype',scenarioId:p.scenarioId||'fixture',level:p.level||0,chapter:p.chapter||'A',cardIds:p.cardIds||[],entityId:p.entityId,phase:p.phase||'unknown',response:p.response,confidence:p.confidence,latencyMs:p.latencyMs||0,hintsUsed:p.hintsUsed||0,riskError:!!p.riskError,explanationScore:p.explanationScore,timestamp:new Date().toISOString(),name};let all=JSON.parse(localStorage.getItem('sa:events')||'[]');all.push(e);localStorage.setItem('sa:events',JSON.stringify(all.slice(-500)));return e}
function entityEncounter(index=0,tier='one'){let e=SA_DATA.entityDefs[index%40],t=e.tiers[tier];return{...e,tier:t,showHint:t.noHint?false:true,sources:Array.from({length:t.sourceConflict},(_,i)=>`conflict-${i+1}`)}}
function restore(){try{return JSON.parse(localStorage.getItem('sa:player'))||initialPlayer()}catch{return initialPlayer()}}
function persist(p){localStorage.setItem('sa:player',JSON.stringify(p));return p}
return{intervals,initialPlayer,termLevel,mastered,schedule,updateCard,gap,practiceFor,rng,candles,riskSize,dqi,validateEvent,event,entityEncounter,restore,persist};})();
