window.MECHANIC_RUNTIME=(()=>{
const typeMap={M01:'recall',M02:'explain',M03:'sequence',M04:'decision',M05:'markup',M06:'replay',M07:'risk',M08:'ohlc',M09:'timeframe',M10:'indicator',M11:'ensemble',M12:'pattern',M13:'timeline',M14:'order',M15:'branch',M16:'dossier',M17:'graph',M18:'ranking',M19:'strategy',M20:'backtest',M21:'sandbox',M22:'bias',M23:'audit',M24:'battle',M25:'chest',M26:'capstone',M27:'seed',M28:'resume',M29:'access',M30:'copy',M31:'clinic',M32:'skill',M33:'review',M34:'sequence',M35:'battle',M36:'capstone'};
const h=(s)=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function widget(m,advanced){let id=m.id,t=typeMap[id],cards=m.cards.map(x=>`<span class="token">${advanced?'CARD HIDDEN':h(x)}</span>`).join('');let common=`<div class="stack">${cards}</div>`;
 if(t==='recall')return common+`<div class="grid"><button class="choice" data-val="ok">Независимое подтверждение</button><button class="choice" data-val="bad">Одна яркая свеча</button></div><label class="card soft">Уверенность <input data-confidence type="range" min="20" max="100" value="60"></label>`;
 if(t==='explain'||t==='capstone')return common+`<textarea data-text placeholder="Сначала объясните: evidence, risk, invalidation"></textarea>`;
 if(t==='sequence')return common+`<p class="meta">Соберите порядок:</p><div class="grid"><button class="choice" data-step="1">1 · Evidence</button><button class="choice" data-step="2">2 · Invalidation</button><button class="choice" data-step="3">3 · Risk cap</button></div><div class="stack" data-order></div>`;
 if(t==='decision'||t==='timeline'||t==='bias')return common+`<div class="grid two"><button class="choice" data-val="ok">${t==='bias'?'Revenge bias':'WAIT'}</button><button class="choice" data-val="ok">NO TRADE</button><button class="choice" data-val="bad">ENTER NOW</button><button class="choice" data-val="bad">Увеличить риск</button></div>`;
 if(t==='markup'||t==='pattern')return `<div class="chart" data-chart tabindex="0" role="button" aria-label="Отметить структурную зону"></div><div class="grid two"><button class="choice" data-val="ok">Под higher low</button><button class="choice" data-val="bad">Ровно −1%</button></div>`;
 if(t==='replay')return `<div class="chart" data-chart></div><div class="row"><span class="badge">Candle <b data-count>16</b>/24</span><button class="tab" data-next>Следующая свеча</button></div>`;
 if(t==='risk'||t==='order')return common+`<div class="card"><label>Deposit <input data-deposit type="number" value="10000"></label><label>Risk % <input data-risk type="number" value="1" step=".25"></label><label>Entry <input data-entry type="number" value="100"></label><label>Stop <input data-stop type="number" value="98"></label><p data-calc class="delta"></p></div>`;
 if(t==='ohlc')return `<div class="card"><label>Open <input data-o type="range" min="80" max="120" value="100"></label><label>High <input data-h type="range" min="80" max="120" value="112"></label><label>Low <input data-l type="range" min="80" max="120" value="94"></label><label>Close <input data-c type="range" min="80" max="120" value="108"></label></div>`;
 if(t==='timeframe'||t==='indicator')return `<div class="chart" data-chart></div><div class="grid two"><button class="choice" data-val="ok">15m: шум</button><button class="choice" data-val="ok">4h: контекст</button><button class="choice" data-val="bad">BUY signal</button></div>`;
 if(t==='ensemble')return `<div class="grid"><button class="source" data-pick="trend">Trend filter</button><button class="source" data-pick="trigger">Trigger</button><button class="source" data-pick="risk">Risk measure</button><button class="source" data-pick="extra">Extra indicator</button></div><p class="meta">Лимит: 1 trend + 1 trigger + 1 risk.</p>`;
 if(t==='branch')return `<textarea data-text placeholder="A — если работает…\nB — если ломается…\nC — если хаос…"></textarea>`;
 if(t==='dossier'||t==='ranking'||t==='graph')return `<div class="grid"><button class="source" data-val="ok"><b>Primary tape</b><small>author/date/incentive verified · 0.91</small></button><button class="source" data-val="bad"><b>Anonymous social post</b><small>position and method missing · 0.28</small></button><button class="source" data-val="ok"><b>Macro calendar</b><small>event context · 0.84</small></button></div>`;
 if(t==='strategy')return `<textarea data-text placeholder="Universe → regime → setup → entry → stop → size → exit → prohibition"></textarea>`;
 if(t==='backtest')return `<div class="card"><div class="row"><span>Wins / Losses</span><b>11 / 9</b></div><div class="row"><span>Avg win / loss</span><b>1.6R / −1R</b></div><p class="delta">Expectancy: +0.43R</p></div><button class="choice" data-val="ok">Выборка недостаточна для обещаний</button>`;
 if(t==='sandbox')return `<div class="card"><label>Risk % <input data-risk-slider type="range" min="1" max="10" value="2"></label><label>Win rate <input type="range" min="20" max="80" value="45"></label><label>R:R <input type="range" min="1" max="4" value="2"></label><p data-ruin class="warn">Ruin pressure: controlled</p></div>`;
 if(t==='audit')return `<div class="card"><p>30 решений заблокированы от редактирования.</p></div><textarea data-text placeholder="Один rule patch — не больше"></textarea>`;
 if(t==='battle')return `<div class="entity" aria-label="Entity encounter">◈</div><div class="grid"><button class="choice" data-step="1">Wait for Retest</button><button class="choice" data-step="2">Define Invalidation</button><button class="choice" data-step="3">Risk Cap</button></div><div class="stack" data-order></div>`;
 if(t==='chest')return `<div class="entity">▣</div><p class="callout">Reward table disclosed. Cosmetic only; no hints, cards or answer protection.</p><button class="choice" data-val="ok">Открыть earned chest</button>`;
 if(t==='seed')return `<div class="card"><label>Scenario seed <input data-seed type="number" value="1701"></label><p class="meta">Одинаковый seed → одинаковый fixture.</p></div>`;
 if(t==='resume')return `<div class="card"><b>Saved state</b><p class="meta">phase=act · answer=sealed · replayIndex=16</p></div><button class="choice" data-val="ok">Resume exact phase</button>`;
 if(t==='access')return `<div class="grid"><button class="choice" data-val="ok">Button alternative</button><button class="choice" data-val="ok">Keyboard path</button><button class="choice" data-val="ok">Screen-reader labels</button></div>`;
 if(t==='copy')return `<div class="tabs"><button class="tab active" data-val="ok">Plain</button><button class="tab" data-val="ok">Guided</button><button class="tab" data-val="ok">Technical</button></div><div class="card"><p>${advanced?'Weigh source quality, regime and strongest alternative.':'Один факт подтверждает идею; один факт её отменяет.'}</p></div>`;
 if(t==='clinic')return `<div class="grid"><button class="choice" data-val="ok">Knowledge gap</button><button class="choice" data-val="ok">Transfer gap</button><button class="choice" data-val="ok">Discipline gap</button><button class="choice" data-val="bad">100 одинаковых повторений</button></div>`;
 if(t==='skill')return `<div class="card"><div class="label">Recognition / Application / Transfer / Explanation / Stability</div>${['R 0.86','A 0.81','T 0.71','X 0.77','S 0.84'].map(x=>`<div class="row"><span>${x}</span><div class="progress" style="width:55%;--p:${+x.slice(2)*100}%"><i></i></div></div>`).join('')}</div>`;
 if(t==='review')return `<div class="stack">${[1,3,7,16,35].map(x=>`<span class="token">+${x} day</span>`).join('')}</div><button class="choice" data-val="ok">Schedule next review</button>`;
 return `<button class="choice" data-val="ok">Safe attempt</button>`}
function bind(modal,m,advanced){let state={selected:null,order:[],replay:16,picks:new Set()};modal.querySelectorAll('[data-val]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.val;modal.querySelectorAll('[data-val]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});modal.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{if(!state.order.includes(b.textContent))state.order.push(b.textContent);modal.querySelector('[data-order]').innerHTML=state.order.map(x=>`<span class="token on">${h(x)}</span>`).join('')});modal.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{let x=b.dataset.pick;if(state.picks.has(x)){state.picks.delete(x);b.classList.remove('selected')}else if(state.picks.size<3){state.picks.add(x);b.classList.add('selected')}else SA.toast('Лимит — три независимые роли')});let chart=modal.querySelector('[data-chart]');if(chart)SA.chart(chart,parseInt(m.id.slice(1)),false);let next=modal.querySelector('[data-next]');if(next)next.onclick=()=>{state.replay=Math.min(24,state.replay+1);modal.querySelector('[data-count]').textContent=state.replay;SA.chart(chart,parseInt(m.id.slice(1)),state.replay>16)};let calc=()=>{let q=SA_ENGINE.riskSize({deposit:+modal.querySelector('[data-deposit]')?.value,riskPct:+modal.querySelector('[data-risk]')?.value,entry:+modal.querySelector('[data-entry]')?.value,stop:+modal.querySelector('[data-stop]')?.value});let e=modal.querySelector('[data-calc]');if(e)e.textContent=q.ok?`Size ${q.size} · risk ${q.risk}`:q.error};modal.querySelectorAll('input').forEach(x=>x.addEventListener('input',calc));calc();let rs=modal.querySelector('[data-risk-slider]');if(rs)rs.oninput=()=>modal.querySelector('[data-ruin]').textContent=+rs.value>4?'Ruin pressure: critical':'Ruin pressure: controlled';return state}
function validate(modal,m,state){let t=typeMap[m.id];if(['explain','capstone','branch','strategy','audit'].includes(t))return (modal.querySelector('[data-text]')?.value.trim().length||0)>=18;if(['sequence','battle'].includes(t))return state.order.length>=3;if(t==='ensemble')return state.picks.size===3;if(t==='replay')return state.replay>16;if(['risk','order'].includes(t))return !!modal.querySelector('[data-calc]')?.textContent.startsWith('Size');if(t==='ohlc'){let o=+modal.querySelector('[data-o]').value,hi=+modal.querySelector('[data-h]').value,lo=+modal.querySelector('[data-l]').value,c=+modal.querySelector('[data-c]').value;return hi>=Math.max(o,c)&&lo<=Math.min(o,c)}return state.selected==='ok'||['markup','pattern','timeframe','indicator','sandbox','skill','seed'].includes(t)}
function open(id){let m=SA_DATA.mechanics.find(x=>x.id===id),advanced=false,state;let o=document.createElement('div');o.className='overlay';function paint(){o.innerHTML=`<div class="modal"><div class="top"><div><div class="label">${m.id} · ${advanced?'ADVANCED':'NOVICE INTRO'}</div><div class="big">${m.icon} ${h(m.name)}</div></div><button class="tab" data-close>×</button></div><p class="callout">${h(m.why)}</p><div class="tabs"><button class="tab ${!advanced?'active':''}" data-mode="novice">Safe attempt</button><button class="tab ${advanced?'active':''}" data-mode="advanced">Advanced</button></div><div class="card soft"><div class="label">${advanced?'CONFLICT + TRANSFER':'NAME → WHY → DEMO → PRACTICE'}</div><p>${advanced?'Названия карт скрыты; добавлен конфликт; объяснение обязательно.':'Без таймера и Entity. Ошибка не повреждает постоянный прогресс.'}</p></div>${widget(m,advanced)}<div data-feedback aria-live="polite"></div><button class="primary" data-check>Проверить acceptance</button><a class="secondary" style="display:grid;place-items:center;text-decoration:none" href="scenario-runner.html#${m.id}">Открыть полный 6-phase scenario</a></div>`;state=bind(o,m,advanced);o.querySelector('[data-close]').onclick=()=>o.remove();o.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{advanced=b.dataset.mode==='advanced';paint()});o.querySelector('[data-check]').onclick=()=>{let ok=validate(o,m,state),f=o.querySelector('[data-feedback]');f.innerHTML=`<div class="card ${ok?'good':'bad'}"><b>${ok?'✓ Fixture passed':'Нужно завершить действие'}</b><p class="meta">${ok?'Событие, state и debrief сохранены.':'Показана конкретная ошибка без раскрытия полного ответа.'}</p></div>`;if(ok){SA_ENGINE.event('answer_submitted',{scenarioId:'scenario-'+m.id.toLowerCase(),level:m.level,chapter:'fixture',cardIds:m.cards,phase:'act',response:{advanced,type:typeMap[m.id]},hintsUsed:0});SA.toast(m.id+' сохранена')}}}paint();document.body.append(o)}
return{open,typeMap,widget,bind,validate};})();
